### ISSUE TITLE
Parity compatibility

### ISSUE THREAD

**Issue by jorisbontje** [ethgasstation/ethgasstation-adaptive-oracle#2]
Unfortunately the Parity compatibility is currently blocked by the lack of `web3.txpool` support in the Parity RPC:

```
Traceback (most recent call last):
  File "ethgasstation.py", line 354, in update_dataframes
    current_txpool = get_txhases_from_txpool(block)
  File "ethgasstation.py", line 95, in get_txhases_from_txpool
    txpoolcontent = web3.txpool.content
  File "/Users/me/.virtualenvs/ethgasstation-adaptive-oracle/lib/python3.6/site-packages/web3/txpool.py", line 9, in content
    return self.web3.manager.request_blocking("txpool_content", [])
  File "/Users/me/.virtualenvs/ethgasstation-adaptive-oracle/lib/python3.6/site-packages/web3/manager.py", line 96, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'Method not found'}
```

See also https://github.com/paritytech/parity/issues/2506

**Comment by ethgasstation** [comment]
There is no way for this to work without getting data from the txpool - Im surprised Parity does not support

**Comment by ligi** [comment]
> Geth-compatible txpool API is there on the roadmap, but without ETA.

so I would just ignore this until they support it ..
